
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/SideNav";
import TopNav from "@/components/TopNav";
import { ContextProvider } from '@/components/Context/AppointmentContext';
import Notification from "@/components/utils/Notification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
        <div className="flex h-full">
        <ContextProvider >
        <Notification />
          <aside className="hidden md:block">
            <Sidebar />
          </aside>
          <main className="flex-1 h-full overflow-auto">
            <TopNav className="md:hidden block" />
            {children}
          </main>
    </ContextProvider>
        </div>
      </body>
    </html>
  );
}